### ISSUE TITLE
Readings have stopped updating

### ISSUE THREAD

**Issue by godfatherjd** [pschluet/daily-bible-readings#25]
Your prayers, Paul. We are using your wonderful plugin for the Antiochian Archdiocese of Australia, New Zealand, and Philippines website: https://www.antiochian.org.au/resources/chapel/daily-bible-readings-and-lectionary/ 
Right now is 11AM 24th December Australian EDST though readings seem to have stalled, with the last reading being from November 4th.
I'm not sure if this is because the content hasn't been updated, or if there is a broken plugin etc.
Thank you for this great gift.
Fr. John
Web Administrator

**Comment by pschluet** [comment]
Fr. John,
Sorry for the delayed response on this! Try deactivating and re-activating the plugin and let me know if that fixes the problem.

**Comment by godfatherjd** [comment]
Christ is Risen,

Thank you for getting back to me and your dedication to preaching the gospel online. Unfortunately I wasn’t able to get it working.

Here is what I tried (in order):

  1.  Purging cache
  2.  Disabling plugin, purge, re-enable
  3.  Disable, delete, reinstall

After the re-install, i.e. Step 3, it came back with a critical error which I have listed below. Please let me know if there is anything you think I am doing wrong, and if you think I can help.
[cid:image001.png@01D63293.71DDA220]

Fatal error: Uncaught Error: Call to a member function get_date() on bool in /home/saintma3/public_html/arch/wp-content/plugins/daily-bible-readings/includes/class-dbr-public-view.php:62 Stack trace: #0 /home/saintma3/public_html/arch/wp-content/plugins/daily-bible-readings/includes/class-dbr-public-view.php(100): DBR_View->get_date_display() #1 /home/saintma3/public_html/arch/wp-content/plugins/daily-bible-readings/includes/class-dbr-public-view.php(40): DBR_View->get_readings_all_display() #2 /home/saintma3/public_html/arch/wp-includes/shortcodes.php(343): DBR_View->shortcode_handler(Array, '', 'daily-bible-rea...') #3 [internal function]: do_shortcode_tag(Array) #4 /home/saintma3/public_html/arch/wp-includes/shortcodes.php(218): preg_replace_callback('/\\[(\\[?)(daily\\...', 'do_shortcode_ta...', '<div class="fus...') #5 /home/saintma3/public_html/arch/wp-includes/class-wp-hook.php(289): do_shortcode('<div class="fus...') #6 /home/saintma3/public_html/arch/wp-includes/plugin.php(206): WP_Hook->apply_filters('<div class in /home/saintma3/public_html/arch/wp-content/plugins/daily-bible-readings/includes/class-dbr-public-view.php on line 62
There has been a critical error on your website.
Learn more about debugging in WordPress.<https://wordpress.org/support/article/debugging-in-wordpress/>
